[package]
name = "bandits"
version = "0.1.0"
authors = ["Evan Czyzycki <eczy3826@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rand_distr = "0.3.0"
csv = "1.1.5"
clap = "2.33.3"